### ISSUE TITLE
Any advantages (or differences) over linaria?

### ISSUE THREAD

**Issue by 87Hz** [CraigCav/css-zero#8]
Not a real issue.
It looks very similar to `linaria`, would you mind listing down the advantages of `css-zero`?
Thanks.

**Comment by CraigCav** [comment]
This repo was heavily inspired by linaria. The biggest behaviorial difference is that linaria doesn't generate atomic CSS. 

For a great overview on atomic CSS (in the context of css-in-js), I'll refer you to this excellent post by  @slorber: https://sebastienlorber.com/atomic-css-in-js

The biggest non-behaviorial difference is that css-zero was primarily just a learning project; if you're looking for something battle tested, linara is likely a much safer bet!

**Comment by slorber** [comment]
thanks :)

Added you to the "list" https://twitter.com/sebastienlorber/status/1264913685841149958
